# Generated by Django 4.1.4 on 2022-12-16 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questionnaires', '0005_questionnaire_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='questionnaire',
            name='short_link',
            field=models.CharField(default='nada', max_length=20),
            preserve_default=False,
        ),
    ]
